// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicGarden.Storage;

namespace MusicGarden.Storage.Migrations
{
    [DbContext(typeof(MusicGardenContext))]
    partial class MusicGardenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicGarden.Domain.Models.SavingPlaylist", b =>
                {
                    b.Property<int>("unique_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playlistname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("unique_ID");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("MusicGarden.Domain.Models.SavingTrack", b =>
                {
                    b.Property<int>("unique_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SavingPlaylistunique_ID")
                        .HasColumnType("int");

                    b.Property<string>("id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trackname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("unique_ID");

                    b.HasIndex("SavingPlaylistunique_ID");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("MusicGarden.Domain.Models.SavingTrack", b =>
                {
                    b.HasOne("MusicGarden.Domain.Models.SavingPlaylist", null)
                        .WithMany("Tracks")
                        .HasForeignKey("SavingPlaylistunique_ID");
                });

            modelBuilder.Entity("MusicGarden.Domain.Models.SavingPlaylist", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
